# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_Rest
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Rest/Dockerfile'
        tags: |
          $(tag)
#- stage: Build_WebSocket
#  displayName: Build image
#  jobs:  
#  - job: Build
#    displayName: Build
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: build
#        dockerfile: '$(Build.SourcesDirectory)/WebSocket/Dockerfile'
#        tags: |
#          $(tag)
- stage: Build_LAvaPodler
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Generate gradle stuff
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'LavaPodler/gradlew'
        workingDirectory: 'LavaPodler'
        tasks: 'wrapper dockerCreateDockerfile'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: false
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        Dockerfile: 'LavaPodler/build/docker/Dockerfile'
        tags: '$(tag)'
      env:
        MySecret: $(Foo)
