version: '3'

services:

  redis:
    image: 'redis'
    ports: 
      - 6379
    container_name: 'redis'
    restart: 'always'

  nats:
    image: 'nats'
    container_name: 'nats'
    restart: 'always'
    ports: 
      - 4222

  lavapodler:
    image: 'lavapod/lavapodler:master'
    container_name: 'lavapod'
    restart: 'always'
    depends_on: 
      - 'nats'
    links: 
      - 'nats'
    environment: 
      - NATS='nats://nats:4222'

  rest:
    image: 'lavapod/rest:master'
    container_name: 'rest'
    restart: 'always'
    ports: 
      - 8080:8080
    depends_on: 
      - 'nats'
    links: 
      - 'nats'
      - 'redis'
      - 'lavapodler'

  websocket:
    image: 'lavapod/websocket:master'
    container_name: 'websocket'
    restart: 'always'
    ports:
      - 8081:8081
    depends_on: 
      - 'nats'
    links: 
      - 'nats'
      - 'redis'
      - 'lavapodler'
    environment: 
      - NATS='nats://nats:4222'
      - REDIS_PORT='6379'
      - REDIS_HOST='redis'