apiVersion: apps/v1
kind: Deployment
metadata:
  name: lavarest
  labels:
    name: lavarest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lavarest
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lavarest
    spec:
      containers:
      - image:  matthis974/dockspace:lavarest-4
        name:  lavarest
        env:
        - name:  LAVA_PORT
          value:  "8000"    
        - name: LAVA_EXTENDED
          value: 'true'
        - name: LAVA_LOGFORMAT
          value: 'dev'
        - name: LAVA_RPC_HOST
          value: lavapod-rabbitmq.rabbitmq
        ports:
          - containerPort: 8000
        resources:
          requests:
            cpu: "1m"
            memory: "20M"
          limits:
            cpu: "1m"
            memory: "50M"
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: lavarest
spec:
  type: ClusterIP
  selector:
    app: lavarest
  ports:
    - port: 80
      targetPort: 8000
