apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: lavapodler
  name: lavapodler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lavapodler
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: lavapodler
    spec:
      containers:
      - env:
        - name: NATS
          value: nats://lavapod:lavapod@nats:4222
        image: lavapod/lavapodler:master
        imagePullPolicy: "Always"
        name: lavapod
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
