apiVersion: v1
kind: Service
metadata:
  annotations:
    lavapod-component: nats
  labels:
    app: nats
  name: nats
spec:
  ports:
  - name: "4222"
    port: 4222
    targetPort: 4222
  selector:
    app: nats