apiVersion: v1
kind: Service
metadata:
  annotations:
    lavapod-component: websocket
  labels:
    app: websocket
  name: websocket
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app: websocket