---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: websocket
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/hostname: ws2lavapod.matthieu-dev.xyz
    external-dns.alpha.kubernetes.io/ttl: "120" #optional
spec:
  rules:
  - host: ws2lavapod.matthieu-dev.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: websocket
          servicePort: 8081