apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    lavapod-component: websocket
  labels:
    app: websocket
  name: websocket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      annotations:
        lavapod-component: websocket
      labels:
        app: websocket
    spec:
      containers:
      - env:
        - name: NATS
          value: nats://lavapod:lavapod@nats:4222
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        image: lavapod/websocket:master
        imagePullPolicy: "Always"
        name: websocket
        ports:
        - containerPort: 8081
      restartPolicy: Always